name: Prebuild devcontainer

on:
  push:
    branches: #[ 2025_prebuilt_container, 2025_test_prebuilt] # Change to main later, please work
      - 2025_prebuilt_container
      - 2025_test_prebuilt
    paths:
      - ".devcontainer/**"
      - "common/requirements.txt"
      - ".github/workflows/devcontainer-prebuild.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # allow pushing to GHCR

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lower-case owner (needed for GHCR image names)
        run: echo "OWNER_LC=${OWNER,,}" >> $GITHUB_ENV
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Define image name
        run: echo "IMAGE=ghcr.io/${OWNER_LC}/uwfe-dev" >> $GITHUB_ENV

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build and push devcontainer image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .devcontainer
          imageName: ${{ env.IMAGE }}
          push: always
          # First push: DO NOT reference tags that don't exist yet.
          # Uncomment cacheFrom after first successful push.
          # cacheFrom: ${{ env.IMAGE }}
          # Multi-arch:
          platform: linux/amd64,linux/arm64